name: image-build
author: rlarkdms
description: 'Use image-build job in github action'
inputs:
  REGISTRY:
    description: 'SET ECR REGISTRY'
    required: true
    default: ''
  REPOSITORY:
    description: 'SET ECR REPOSITORY'
    required: true
    default: ''
  DOCKERFILE_FATH:
    description: 'SET dockerfile path'
    required: false
    default: 'dockerfile'

runs:
  using: "composite"
  steps:
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
    with:
      mask-password: 'true'
  - name: docker build & push
    shell: bash
    run: |
      docker build -f ${{ inputs.DOCKERFILE_FATH }} --tag ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ github.sha }} .
      docker push ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}:${{ github.sha }}